import Link from 'next/link';
import { Logo } from '@/components/logo';

export default function TermsPage() {
  return (
    <div className="flex min-h-screen flex-col">
       <header className="sticky top-0 z-50 w-full border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
        <div className="container flex h-14 items-center justify-between">
          <div className="mr-4 flex">
            <Link href="/" className="mr-6 flex items-center space-x-2">
              <Logo />
            </Link>
          </div>
        </div>
      </header>
      <main className="flex-1">
        <div className="container py-20">
          <article className="prose prose-lg max-w-none text-muted-foreground prose-h1:font-headline prose-h1:text-foreground prose-h2:font-headline prose-h2:text-foreground prose-h2:mt-12 prose-h2:mb-4 prose-h3:font-headline prose-h3:text-foreground prose-headings:font-headline prose-strong:text-foreground">
            <h1>Terms of Service</h1>
            <p>Effective Date: {new Date().toLocaleDateString()}</p>
            <p>Last Updated: {new Date().toLocaleDateString()}</p>

            <p>Welcome to Close Kit, a SaaS platform designed for contractors. These Terms of Service (the "Terms" or "Agreement") govern Your access and use of the Close Kit Service. By accessing, purchasing, or using the Service, You agree to be bound by these Terms.</p>

            <h2>1. Definitions</h2>
            <p><strong>1.1. "Close Kit," "We," "Us," or "Our"</strong> refers to the Close Kit application and its operators.</p>
            <p><strong>1.2. "Customer" or "You"</strong> refers to the entity or individual subscribing to the Service.</p>
            <p><strong>1.3. "Service"</strong> means the cloud-based Close Kit platform, including the web portal, AI tools, and all related documentation.</p>
            <p><strong>1.4. "Authorized User"</strong> means any employee, contractor, or agent of Customer who is granted access to the Service by an administrator of the Customer's account.</p>
            <p><strong>1.5. "Customer Content"</strong> means all data, information, files, Price Books, and other content uploaded or created by Customer or its Authorized Users within the Service.</p>
            <p><strong>1.6. "AI Services" or "AI Output"</strong> refers to any text, recommendation, or analysis generated by the Service’s machine learning models (e.g., GBB options, narrative translations).</p>

            <h2>2. Acceptance of Terms</h2>
            <p>2.1. These Terms constitute a binding legal agreement. By creating an account or using the Service, You confirm that You have read, understood, and agree to be legally bound by this Agreement. If You are entering into these Terms on behalf of an entity, You represent that You have the authority to bind that entity to these Terms.</p>

            <h2>3. License and Restrictions</h2>
            <p><strong>3.1. Grant of License:</strong> We grant you a non-exclusive, non-transferable, revocable license to access and use the Service for your internal business operations during your subscription term, in accordance with your chosen service plan.</p>
            <p><strong>3.2. Restrictions:</strong> You shall not, and shall ensure your Authorized Users do not: (i) sublicense, sell, or resell the Service; (ii) reverse engineer or attempt to derive the source code of the Service or its AI models; (iii) use the Service to build a competitive product; or (iv) use the Service in any manner that violates any applicable law.</p>
            
            <h2>4. Financial Terms and Payment</h2>
            <p><strong>4.1. Fees:</strong> Customer agrees to pay the subscription fees for their chosen service plan (e.g., Solo, Team). Fees are billed monthly in advance.</p>
            <p><strong>4.2. Recurring Billing:</strong> The Service is a recurring subscription. You authorize Us (or our third-party payment processor) to charge your payment method for all recurring fees.</p>
            <p><strong>4.3. Payment Processor:</strong> We use third-party payment processing services (PayPal) to handle all financial transactions. You agree to be bound by the terms and privacy policies of the designated Payment Processor.</p>
            <p><strong>4.4. Suspension:</strong> If any payment fails, We reserve the right to suspend or terminate access to the Service.</p>
            
            <h2>5. Customer Responsibilities and Liability for AI Output</h2>
            <p><strong>5.1. AI Output Disclaimer:</strong> The AI Services generate outputs using machine learning models. AI Output is probabilistic, for informational purposes only, and does not constitute professional advice. We make no warranty regarding the accuracy or reliability of AI Output.</p>
            <p><strong>5.2. Mandate for Human Review:</strong> You acknowledge and agree that you are solely responsible for all decisions made and actions taken based on the use of AI Services. You must conduct an independent, professional human review of all AI Output before presenting any proposal to an end-client or executing any work.</p>
            <p><strong>5.3. User Accountability:</strong> You are responsible for the actions of your Authorized Users and for maintaining the confidentiality of your login credentials.</p>

            <h2>6. Intellectual Property and Data</h2>
            <p><strong>6.1. Close Kit IP:</strong> We retain all right, title, and interest in and to the Service, including the underlying software and AI models.</p>
            <p><strong>6.2. Customer Content Ownership:</strong> You retain all ownership rights in and to your Customer Content, including your Price Books and client lists.</p>
            <p><strong>6.3. License to Customer Content:</strong> You grant Us a non-exclusive, worldwide, royalty-free license to use, process, and store your Customer Content solely as necessary to provide, maintain, and support the Service.</p>
            <p><strong>6.4. Prohibition of AI Training:</strong> We will not use your Customer Content to train, develop, or improve any generalized Large Language Model (LLM) or generative AI model. We may use aggregated and anonymized usage data for platform improvement.</p>

            <h2>7. Termination</h2>
            <p><strong>7.1. Termination by You:</strong> You may cancel your subscription at any time via your account settings. The termination will be effective at the end of the current billing cycle.</p>
            <p><strong>7.2. Termination by Us:</strong> We may suspend or terminate this Agreement immediately if you materially breach these Terms (e.g., non-payment, unauthorized use).</p>
            <p><strong>7.3. Data Return:</strong> Upon termination, you will have a limited time (e.g., thirty days) to export your Customer Content before it is securely deleted.</p>
            
             <h2>8. Limitation of Liability</h2>
            <p>IN NO EVENT WILL WE BE LIABLE FOR ANY INDIRECT, INCIDENTAL, PUNITIVE, SPECIAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST PROFITS OR REVENUE. OUR TOTAL CUMULATIVE LIABILITY SHALL NOT EXCEED THE FEES PAID BY YOU IN THE TWELVE (12) MONTH PERIOD PRECEDING THE CLAIM.</p>

          </article>
        </div>
      </main>
    </div>
  );
}
