import Link from 'next/link';
import { Logo } from '@/components/logo';

export default function TermsPage() {
  return (
    <div className="flex min-h-screen flex-col">
       <header className="sticky top-0 z-50 w-full border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
        <div className="container flex h-14 items-center justify-between">
          <div className="mr-4 flex">
            <Link href="/" className="mr-6 flex items-center space-x-2">
              <Logo />
            </Link>
          </div>
        </div>
      </header>
      <main className="flex-1">
        <div className="container py-20">
          <h1 className="font-headline text-4xl font-bold tracking-tight lg:text-5xl">
            Terms of Service
          </h1>
          <div className="prose prose-lg mt-6 max-w-none text-muted-foreground">
            <p>Effective Date: {new Date().toLocaleDateString()}</p>
            <p>Last Updated: {new Date().toLocaleDateString()}</p>

            <p>Welcome to Close Kit, a vertical SaaS platform designed to streamline HVAC proposal generation and field service management. These Terms of Service (the "Terms" or "Agreement") govern Your access and use of the Close Kit Service. By accessing, purchasing, or using the Service, You agree to be bound by these Terms and any policies referenced herein.</p>

            <h2>1. Definitions</h2>

            <p>1.1. "Close Kit," "We," "Us," or "Our" refers to Close Kit.</p>
            <p>1.2. "Customer" or "You" refers to the entity or organization subscribing to the Service.</p>
            <p>1.3. "Service" means the cloud-based AI HVAC Proposal Platform, including the web portal, mobile applications, APIs, and all related documentation.</p>
            <p>1.4. "Authorized User" means any employee, contractor, or agent of Customer who is granted access to the Service by Customer, regardless of role (e.g., Administrator, Sales Rep, Technician).</p>
            <p>1.5. "Customer Content" means all data, information, files (including architectural plans), materials, Price Books, and other content uploaded, submitted, or otherwise transmitted by Customer or its Authorized Users into the Service.</p>
            <p>1.6. "AI Services" or "AI Output" refers to any cost estimate, technical specification, configuration, recommendation, graphical representation, or text generated by the Service’s machine learning models.</p>

            <h2>2. Acceptance of Terms</h2>

            <p>2.1. These Terms constitute a binding legal agreement. By clicking "I Accept" or by using the Service, You confirm that You have read, understood, and agree to be legally bound by this Agreement. If You are entering into these Terms on behalf of an entity, You represent that You have the authority to bind that entity to these Terms.</p>

            <h2>3. License and Restrictions</h2>
            <p>3.1. Grant of License: Close Kit grants Customer a non-exclusive, non-transferable, revocable license to access and use the Service solely for its internal business operations during the subscription term, strictly in accordance with these Terms and the applicable service plan, which typically limits use by the number of simultaneous mobile users or total named users.</p>
            <p>3.2. Restrictions: Customer shall not, and shall ensure its Authorized Users do not: (i) sublicense, sell, resell, or otherwise commercially exploit the Service; (ii) reverse engineer or attempt to derive the source code of the underlying AI models; (iii) use the Service to build a competitive product or service; or (iv) use the Service in any manner that violates any applicable law or regulation.</p>

            <h2>4. Financial Terms and Payment</h2>
            <p>4.1. Fees: Customer agrees to pay the subscription fees defined in the Customer’s chosen service plan (e.g., Core, Grow, Plus, tiered by features and user limits). Fees are billed Monthly/Annually in advance.</p>
            <p>4.2. Recurring Billing: The Service operates on a recurring subscription model. Customer authorizes Close Kit (or its designated third-party payment processor) to charge the payment method on file for all recurring fees, including any applicable taxes or add-on service charges (e.g., additional users).</p>
            <p>4.3. Payment Processor: Close Kit utilizes third-party payment processing services, including but not limited to PayPal/Braintree, to handle all financial transactions. Customer agrees to be bound by the terms and privacy policies of the designated Payment Processor.</p>
            <p>4.4. Dunning and Suspension: If any payment fails, Close Kit reserves the right to suspend or terminate access to the Service immediately following a standard dunning period, upon written or electronic notice to the Customer.</p>
            <p>4.5. Dispute Resolution for Fees: Customer must notify Close Kit in writing of any disputed charges appearing on the billing statement or invoice within ninety (90) calendar days of the date the data is made available to the Customer through the Service or the Braintree Payment Services. Failure to report discrepancies within this timeframe constitutes acceptance of the charge.</p>
            
            <h2>5. Customer Responsibilities and Liability Shield for AI Output</h2>
            <p>5.1. AI Output Disclaimer: The AI Services within the Close Kit generate outputs (including pricing, configuration, and technical suggestions) using machine learning models that are based on historical data patterns and inputs provided by the Customer. AI Output is probabilistic, for informational purposes only, and does not constitute professional engineering, financial, or legal advice.</p>
            <p>5.2. Mandate for Human Review: Customer and its Authorized Users acknowledge and agree that they are solely responsible for all decisions made, advice given, and actions taken based on the use of AI Services. The Customer must conduct independent, professional human review of all AI Output, including verifying all costs, profit margins, technical specifications (e.g., load calculations, equipment sizing), and proposed pricing before presenting any proposal to an end-client or executing any work.</p>
            <p>5.3. No Warranty of Accuracy: Close Kit makes no warranty or representation regarding the accuracy, completeness, or reliability of the AI Output.</p>
            <p>5.4. User Accountability: Customer is responsible for the acts and omissions of its Authorized Users and agrees to ensure that all such users comply fully with these Terms. Customer is solely responsible for maintaining the confidentiality and security of all login credentials and access controls.</p>

            <h2>6. Intellectual Property and Data</h2>
            <p>6.1. Close Kit IP: Close Kit retains all right, title, and interest in and to the Service, the underlying software, algorithms, methodologies, and the AI models, including all intellectual property rights therein.</p>
            <p>6.2. Customer Content Ownership: Customer retains all ownership rights in and to the Customer Content, including proprietary Price Books and client lists.</p>
            <p>6.3. License to Customer Content: Customer grants Close Kit a non-exclusive, worldwide, royalty-free license to use, process, and store the Customer Content solely as necessary to provide, maintain, and support the Service under these Terms.</p>
            <p>6.4. Prohibition of AI Training: Close Kit explicitly agrees that it shall not use, access, or incorporate Customer Content (including PII, proposal data, or proprietary Price Book information) to train, develop, or improve any generalized Large Language Model (LLM) or generative AI model unless express, written, separate consent is obtained from the Customer. Close Kit may, however, use aggregated and anonymized usage data and metadata for platform improvement, provided such data cannot be reasonably used to identify the Customer or its specific pricing strategies.</p>

            <h2>7. Indemnification and Limitation of Liability</h2>
            <p>7.1. Mutual Indemnification: Standard mutual indemnification applies, requiring: (i) Close Kit to indemnify Customer against third-party claims alleging that the Service, as delivered, infringes a third party’s intellectual property rights; and (ii) Customer to indemnify Close Kit against claims arising from (a) breach of Section 5 (User Accountability, AI Disclaimer), (b) infringement by Customer Content, or (c) Customer's failure to obtain necessary privacy consents (e.g., employee location tracking).</p>
            <p>7.2. Limitation of Liability: EXCEPT FOR CLAIMS ARISING OUT OF GROSS NEGLIGENCE, WILLFUL MISCONDUCT, FRAUD, OR BREACH OF CONFIDENTIALITY, CLOSE KIT’S TOTAL CUMULATIVE LIABILITY, WHETHER BASED ON AN ACTION IN CONTRACT, TORT, OR OTHERWISE, SHALL NOT EXCEED THE FEES PAID OR PAYABLE BY CUSTOMER UNDER THIS AGREEMENT IN THE TWELVE (12) MONTH PERIOD PRECEDING THE CLAIM OR ACTION.</p>
            <p>7.3. Exclusion of Damages: IN NO EVENT WILL EITHER PARTY BE LIABLE FOR ANY INDIRECT, INCIDENTAL, PUNITIVE, SPECIAL, OR CONSEQUENTIAL DAMAGES, INCLUDING, WITHOUT LIMITATION, LOST PROFITS, LOST REVENUE, OR LOST BUSINESS OPPORTUNITIES, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>

            <h2>8. Termination</h2>
            <p>8.1. Termination by Customer: Customer may terminate its subscription in accordance with the terms of its service plan (e.g., upon end of the current term).</p>
            <p>8.2. Termination by Close Kit: Close Kit may suspend or terminate this Agreement immediately if Customer or any Authorized User materially breaches these Terms (e.g., non-payment, unauthorized use, security compromise).</p>
            <p>8.3. Data Return: Upon termination, Close Kit will make Customer Content available for export for a limited time (e.g., thirty (30) days) before initiating secure deletion.</p>
          </div>
        </div>
      </main>
    </div>
  );
}
